### ISSUE TITLE
(Possible) problem with nested folders in collection

### ISSUE THREAD

**Issue by thisisevanfox** [rzuppur/rekordfix#1]
Hi,

I just tried your application as the features sound really useful. I exported the XML and loaded it into the program, unfortunately it crashes with the error message:
![image](https://user-images.githubusercontent.com/43059689/195406720-35af62e7-fd38-4199-b3eb-081c14915bbb.png)

I have about 15000 tracks in my collection divided in a folder structure. I checked the code and I think the program can't handle my folder structure. The folder structure looks like this:
![image](https://user-images.githubusercontent.com/43059689/195406757-8d645c20-994e-4ac7-b9c8-b49bbbd3f2d4.png)

As you can see, there are many folders with nested folders and playlists underneath.

I'm running Rekordbox 6.6.4. 

Is there a chance to get this fixed?

Kind regards
Johannes

**Comment by thisisevanfox** [comment]
The error has nothing to do with nested folders, but with empty ones. I actually had a few empty folders in my collection that provoked the error.

In the XML it looks like this:
`<NODE Name="EmptyFolder" Type="0" Count="0" />`

**Comment by rzuppur** [comment]
Hi, thanks for the detailed bug report! Empty folders fix has been implemented in the latest version, please let me know if you experience any more issues 🙂
